### Health check
GET http://localhost:3000/health

### Hello with query param
GET http://localhost:3000/hello?name=Lenovo

### Echo JSON
POST http://localhost:3000/echo
Content-Type: application/json

{
  "example": true,
  "msg": "hello"
}
